In [28]:
# OPERACIONES MATEMATICAS
import numpy as np

In [29]:
a1= np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])

In [30]:
print(a1+a2) # Suma
print(a1-a2) # Resta
print(a1*a2) # Producto (a1ya2= #Elementos)
print(a1/a2) # Producto (a1ya2= #Elementos)
print(a1**a2) # Potencia (a1ya2= #Elementos)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]


dtype('int32')

In [32]:
b=np.array([True,False,2,2.563])
b.dtype

dtype('float64')

In [33]:
c=np.array(['Hola','Hi','Holis'])
c.dtype
c.isnumeric()


dtype('<U5')

# Copiando Arrays

In [40]:
a3=np.arange(10,80,10)
a3

array([10, 20, 30, 40, 50, 60, 70])

In [41]:
sub_a3= a3[:4]    # Sub Objeto de a3
sub_a3

array([10, 20, 30, 40])

In [42]:
sub_a3*=2   # Multiplico sub_a3 por 2
sub_a3

array([20, 40, 60, 80])

In [37]:
print(id(a3))
print(id(sub_a3))

2644814379504
2644814216624


In [44]:
c=a3.copy()
c*=2
print(c)
print(a3)

[ 40  80 120 160 100 120 140]
[20 40 60 80 50 60 70]


# RECORRIENDO ARRAYS

In [46]:
d1= np.array([1.5,'b',True,4])
d1

array(['1.5', 'b', 'True', '4'], dtype='<U32')

In [ ]:
for i in d1: # Recorre i en d1
    print(i)

In [51]:
d2= np.array([[1.5,'b',True,4],range(0,4)])
d2

array([['1.5', 'b', 'True', '4'],
       ['0', '1', '2', '3']], dtype='<U32')

In [54]:
for d1 in d2: 
    print(d1)

['1.5' 'b' 'True' '4']
['0' '1' '2' '3']


In [55]:
for d1 in d2:
    for i in d1:
        print(d1)

['1.5' 'b' 'True' '4']
['1.5' 'b' 'True' '4']
['1.5' 'b' 'True' '4']
['1.5' 'b' 'True' '4']
['0' '1' '2' '3']
['0' '1' '2' '3']
['0' '1' '2' '3']
['0' '1' '2' '3']


In [56]:
d3=np.array([[range(3),range(3,6),range(6,9)]])
d3

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [57]:
for d2 in d3:
    print(d2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [58]:
for d2 in d3:
    for d1 in d2:
        print(d1)

[0 1 2]
[3 4 5]
[6 7 8]


In [59]:
for d2 in d3:
    for d1 in d2:
        for i in d1:
            print(i)

0
1
2
3
4
5
6
7
8


In [62]:
for i in d3.reshape(-1):     # Imprime todo el arreglo
    print(i)

0
1
2
3
4
5
6
7
8


In [64]:
for i in d3.nditer(d3):
    print(i)

AttributeError: 'numpy.ndarray' object has no attribute 'nditer'

#Contatenar Arrays

In [66]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a3=np.concatenate((a1,a2))
print(a3)

[ 1  2  3  4  5  6  7  8  9 10]


In [68]:
b1=np.array([[-3,-2.5],[-2,-1.5],[-1,-0.5]])
b2=np.array([[0.5,1],[1.5,2],[2.5,3]])
print(b1)
print(b2)

[[-3.  -2.5]
 [-2.  -1.5]
 [-1.  -0.5]]
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


In [70]:
b3=np.concatenate((b1,b2), axis=0)  # Inserto matrices b1,b2 en matris b3
print(b3)

[[-3.  -2.5]
 [-2.  -1.5]
 [-1.  -0.5]
 [ 0.5  1. ]
 [ 1.5  2. ]
 [ 2.5  3. ]]


In [83]:

c1=np.array([[-10,-9],[-8,7],[-6,-5],[-4,-3],[-2,-1],[0,0]])
c2=np.array([[0,1],[2,3],[4,5],[6,7],[8,9]])
print('c1=',c1)
print('c2=',c2)


c1= [[-10  -9]
 [ -8   7]
 [ -6  -5]
 [ -4  -3]
 [ -2  -1]
 [  0   0]]
c2= [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [84]:
c=np.concatenate((c1,c2),axis=0) # axis= puede cambiar, 
print(c)

[[-10  -9]
 [ -8   7]
 [ -6  -5]
 [ -4  -3]
 [ -2  -1]
 [  0   0]
 [  0   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]]


#Stack

In [85]:
a1=np.array([1,2,3])
a2=np.array([7,8,9])

In [ ]:
a=np.stack((a1,a2), axis=0)  # apilo uno sobre otro 
print(a)
a=np.stack((a1,a2), axis=1)  # apilo uno sobre otro 
print(a)

In [98]:
a1=np.array([1,2,3])
a2=np.array([7,8,9])

a= np.vstack((a1,a2)) 
print(a)
a= np.dstack((a1,a2))
print(a)

[[1 2 3]
 [7 8 9]]
[[[1 7]
  [2 8]
  [3 9]]]


In [104]:
b1=np.array([[-6,-5],[-4,-3],[-2,-1],[0,0]])
b2=np.array([[0,1],[2,3],[4,5]])
print(b1)
print(b2)

[[-6 -5]
 [-4 -3]
 [-2 -1]
 [ 0  0]]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
b=np.dstack((b1,b2),axis=0) # Apile de maneraHorizontal
print(b)

# DIVISION ARRAYS

In [110]:
x= np.array([1,2,3,4,5,6,7,8])
print(x)
#.array_split(array,dicivon)

[1 2 3 4 5 6 7 8]


In [113]:
y=np.array_split(x,4)   # Corto x en 4 elemntos
print(y)

[array([1, 2]), array([3, 4]), array([5]), array([6]), array([7]), array([8])]


In [115]:
a=np.array([[1,2,3,4], 
             [5,6,7,8],
             [9,19,11,12],
             [13,14,15,16]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 19, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
for i in np.hsplit(a,2):
    print(i)

# ARRAYS TRANSPUESTO

In [ ]:
q=np.array([[1,2,3],[4,5,6]])
print(q)
print(q.T)
print(q.T.T)

In [128]:
arr_1=np.arange(0,5)
arr_2=np.array([8,-1,-9,4,2])
print(arr_1)
print(arr_2)

[0 1 2 3 4]
[ 8 -1 -9  4  2]


In [135]:
np.add(arr_2,arr_1)  # Suma
np.sqrt(arr_1)       # Raiz
np.power(arr_1,3)    # Potencia
np.sign(arr_2)       # Signo
np.sin(arr_2)        # Seno
np.cos(arr_2)        # Coseno
np.maximum(arr_1,arr_2)

array([8, 1, 2, 4, 4])

In [138]:
print(arr_1)
print(arr_2)
np.maximum(arr_1,arr_2) # Compara Maximo

[0 1 2 3 4]
[ 8 -1 -9  4  2]


array([8, 1, 2, 4, 4])

In [137]:
print(arr_1)
print(arr_2)
np.equal(arr_1,arr_2) # Compara Iguales

[0 1 2 3 4]
[ 8 -1 -9  4  2]


array([False, False, False, False, False])

In [139]:
print(arr_1)
print(arr_2)
np.greater(arr_1,arr_2) # Compara Iguales

[0 1 2 3 4]
[ 8 -1 -9  4  2]


array([False,  True,  True, False,  True])

In [ ]:
print(arr_2)
np.abs(arr_2) # Valor Absoluto

# NUMEROS ALETORIOS

In [ ]:
np.random.rand(5,3)   # Genera arreglos D1 Y D2 aletorios

In [149]:
np.random.uniform(10,size=[2,2,2])  # Genera arreglos D3 aletorios

array([[[5.96663548, 1.69900275],
        [7.55217425, 4.1402309 ]],

       [[3.13050544, 2.43739356],
        [5.80045927, 8.19395834]]])

In [153]:
np.random.randint(10)   # aletorios entero

7

# FILTRADOS DE LOS ARRAYS

In [157]:
a1=np.random.randint(-1,2,10)  # Aletorio enre -1 a 1y se repite 10 veces
a

array([ 1,  1,  0, -1,  0,  1,  0,  1,  1,  0])

In [160]:
a2= np.array([True,True,True,False])
print(a2.all())   # Todos son Verdaderos?
print(a2.any())   # Por lo menos uno verdadero?

False
True


In [165]:
a3=np.random.uniform(0,5,size=[3,3]) # Gnero matriz 3x3
a3

array([[4.00201617, 1.04444681, 2.99761345],
       [1.49919605, 0.15330049, 3.29149555],
       [4.68024566, 2.05499153, 4.59752872]])

In [166]:
a3f=np.where(a3>=3,-a3*10,a3)  # Cambiar elemento
a3f

array([[-40.0201617 ,   1.04444681,   2.99761345],
       [  1.49919605,   0.15330049, -32.91495548],
       [-46.80245662,   2.05499153, -45.97528723]])