In [1]:
"""
Ejercicio 5 a  - ARX MAX
   
@authors: Jeferson Gallego Chaverra
          Pedro Alejendro Snachez Osorio
          Victor Alfonso Moyano Echeverri 
"""
import numpy as np 
from control import *
import numpy as np 
from control import *


## Ejercicio #1

In [2]:
## Definicion de la FTP y su muestreo 
a = [1.28855,0]
b = [1,0.09831,0.25118]
T=1
gd = tf(a,b,T)
print(gd)


        1.289 z
------------------------
z^2 + 0.09831 z + 0.2512

dt = 1



In [3]:
t,yd = step_response(gd,7)
print(yd)

[0.         1.28855    1.16187265 0.85066831 0.91308163 0.98511408
 0.96235559 0.94649987]


In [4]:
yn = [-0.034766,1.248384,1.210693,0.753457,1.032330,1.018659,0.878476,0.963983]
e = yn - yd
print(e)

[-0.034766   -0.040166    0.04882035 -0.09721131  0.11924837  0.03354492
 -0.08387959  0.01748313]


In [5]:
matrix = [[0,0,0,0],[0.034766,0,1,-0.034766],[-1.248384,0.034766,1,-0.04016],[-1.210693,-1.248384,1,0.04882],[-0.753457,-1.210693,1,-0.09721],[-1.032330,-0.753457,1,0.119248],[-1.018659,-1.032330,1,0.033544],[-0.878476,-1.018659,1,-0.08387]]

In [6]:
matrix[5][0]

-1.03233

In [7]:
matrixT =np.transpose(matrix)

In [8]:
phi1= np.dot(matrixT,matrix)

phi1

array([[ 6.46823775,  5.10448956, -6.107233  , -0.02053145],
       [ 5.10448956,  5.69651766, -5.228757  ,  0.01630737],
       [-6.107233  , -5.228757  ,  7.        , -0.054394  ],
       [-0.02053145,  0.01630737, -0.054394  ,  0.03703414]])

In [9]:
phinv= np.linalg.inv(phi1)
phinv

array([[ 1.14386781, -0.32062188,  0.77333855,  1.91117566],
       [-0.32062188,  0.65335781,  0.20705155, -0.16133813],
       [ 0.77333855,  0.20705155,  0.98610334,  1.78590363],
       [ 1.91117566, -0.16133813,  1.78590363, 30.75574813]])

In [10]:
phimax = np.dot(phinv , matrixT)

phimax.shape

(4, 8)

In [11]:
thetaLS = np.dot(phimax, yn)
thetaLS

array([ 0.06488912,  0.25402927,  1.25732502, -0.53787476])

In [12]:
num = [1.25732502,0]
den = [1,0.06488912,0.25402927]
T=1
gd2 = tf(num,den,T)
print(gd2)


        1.257 z
-----------------------
z^2 + 0.06489 z + 0.254

dt = 1



In [13]:
t,yd2 = step_response(gd2,7)
print(yd2)

[0.         1.25732502 1.17573831 0.86163504 0.90274234 0.97986634
 0.96441938 0.94582996]


In [14]:
e2 = yn - yd2

In [15]:
e2T = np.transpose(e2)
e2T

array([-0.034766  , -0.00894102,  0.03495469, -0.10817804,  0.12958766,
        0.03879266, -0.08594338,  0.01815304])

In [16]:
ECMARMAX = (np.dot(e2,e2T))/8
ECMARMAX

0.005028320616253578

In [17]:
eT = np.transpose(e)
eT

array([-0.034766  , -0.040166  ,  0.04882035, -0.09721131,  0.11924837,
        0.03354492, -0.08387959,  0.01748313])

In [18]:
ECMARX = (np.dot(e,eT))/8
ECMARX


0.0046677912666269325

In [19]:
ECMARMAX, ECMARX

(0.005028320616253578, 0.0046677912666269325)

## Ejercicio #2

In [20]:
yn2=[-0.092550,0.801718,1.191506,1.562065,1.804596,1.852282,2.025160,1.842214]
un2 =[1,1,1,1,1,1,1,1]

np.shape(un2)

(8,)

In [21]:
ph2=[[0,0],[-0.092550,1],[0.801718,1],[1.191506,1],[1.562065,1],[1.804596,1],[1.852282,1],[2.025160,1]]
np.shape(ph2)

(8, 2)

In [22]:
ph2T= np.transpose(ph2)
phaux= np.dot(ph2T,ph2)

In [23]:
phaux2= np.linalg.inv(phaux)

In [24]:
ph2max = np.dot(phaux2,ph2T)
np.shape(ph2max)

(2, 8)

In [25]:
ThetaLS2 = np.dot(ph2max, yn2)
ThetaLS2

array([0.57004877, 0.83808173])

In [26]:
num2 = [227.4005]
den2 = [1,352.0188]
T2=0.5
Gz2 = tf(num2,den2,T2)
Gz2

TransferFunction(array([227.4005]), array([  1.    , 352.0188]), 0.5)

In [27]:
t,yd3 = step_response(Gz2,3.5)
print(yd3)

[ 0.00000000e+00  2.27400500e+02 -7.98218506e+04  2.80990195e+07
 -9.89138289e+09  3.48195274e+12 -1.22571282e+15  4.31473957e+17]


In [28]:
e3 = yn2 - yd3
print(e3)

[-9.25500000e-02 -2.26598782e+02  7.98230421e+04 -2.80990179e+07
  9.89138289e+09 -3.48195274e+12  1.22571282e+15 -4.31473957e+17]
