In [1]:
"""
Ejercicio 5 b  - ARX MAX
   
@authors: Jeferson Gallego Chaverra
          Pedro Alejendro Snachez Osorio
          Victor Alfonso Moyano Echeverri 
"""
import numpy as np 
from control import *

In [2]:
yn =[-0.092550,0.801718,1.191506,1.562065,1.804596,1.852282,2.025160,1.842214]
un =[1,1,1,1,1,1,1,1]

phi propuesto : -y[k-1], u[k-1]

In [3]:
phi = [[0,0],[0.092550,1],[-0.801718,1],[-1.191506,1],[-1.562065,1],[-1.804596,1],[-1.852282,1],[-2.025160,1]]

In [4]:
phiT = np.transpose(phi)

In [5]:
phixphiT = np.dot(phiT, phi)

In [6]:
phinv = np.linalg.inv(phixphiT)

In [7]:
phimas = np.dot(phinv, phiT)

In [8]:
ThetaLS = np.dot(phimas, yn)
ThetaLS

array([-0.57004877,  0.83808173])

In [9]:
num = [0.83808]
den = [1, -0.57004]
T = 0.5
gs = tf(num, den, T)
gs

TransferFunction(array([0.83808]), array([ 1.     , -0.57004]), 0.5)

In [10]:
t,yd = step_response(gs, 3.5)
print(yd)

[0.         0.83808    1.31581912 1.58814953 1.74338876 1.83188133
 1.88232563 1.9110809 ]


In [11]:
e = yn - yd
e

array([-0.09255   , -0.036362  , -0.12431312, -0.02608453,  0.06120724,
        0.02040067,  0.14283437, -0.0688669 ])

ARMAX

phi propuesto : -y[k-1], u[k-1, e[k-1]

In [12]:
phi2 = [[0,0,0],[0.092550,1,-0.09255],[-0.801718,1,-0.036362],[-1.191506,1,0.83116512],[-1.562065,1,0.92939371],[-1.804596,1,1.32716394],[-1.852282,1,1.28635737],[-2.025160,1,1.50967968]]

In [13]:
phi2T = np.transpose(phi2)

In [14]:
phi2Txphi2 = np.dot(phi2T, phi2)

In [15]:
phi2inv = np.linalg.inv(phi2Txphi2)

In [16]:
phimas2 = np.dot(phi2inv, phi2T)

In [17]:
ThetaLS2 = np.dot(phimas2, yn)
ThetaLS2

array([-0.47852848,  0.86551378,  0.11206349])

In [18]:
num2 = [0.86551]
den2 = [1, -0.47852]
gs2 = tf(num2, den2, T)
gs2

TransferFunction(array([0.86551]), array([ 1.     , -0.47852]), 0.5)

In [19]:
t,yd2 = step_response(gs2, 3.5)
print(yd2)

[0.         0.86551    1.27967385 1.47785953 1.57269534 1.61807617
 1.63979181 1.65018318]


In [20]:
e2 = yn - yd2
e2

array([-0.09255   , -0.063792  , -0.08816785,  0.08420547,  0.23190066,
        0.23420583,  0.38536819,  0.19203082])

In [21]:
eT = np.transpose(e)
eT2 = np.transpose(e2)

In [22]:
ECMARX = (np.dot(e, eT)/8)
ECMARMAX = (np.dot(e2, eT2)/8)
ECMARX, ECMARMAX

(0.0069160841976473745, 0.04018922672863866)