In [1]:
# Ejercicio 3   Estimacion con Vector de Pesos 
# JEFRSON GALLEGO, VICOR MOYANO, PEDRO SANCHEZ

from sympy import MatrixSymbol, Matrix, Identity
import sympy as sym
import pandas as pd
sym.init_printing()
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import control
import random

In [2]:
N = 5
t = np.linspace(0,4,5,dtype = "int")

In [3]:
ym = np.array([0.007, 35.096, 60.409, 75.9, 81.609])
t,ym

(array([0, 1, 2, 3, 4]),
 array([7.0000e-03, 3.5096e+01, 6.0409e+01, 7.5900e+01, 8.1609e+01]))

In [4]:
ones = np.ones(N)
phi = np.array([ones, t, t**2]).transpose()
phi

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.]])

In [5]:
# JUGAR CON EL VECTOR DE PESOS
var = np.array([0.063,0.062,0.200,15600,0.25]) 
#var = np.array([0.060,0.070,0.261,15600,0.20]) 
#var = np.array([0.063,0.062,0.251,15625,0.25]) 

_var = var**0.5   # Saco Raiz
W = np.eye(N)*var
_W = np.eye(N)*_var    
W ,_W

(array([[6.30e-02, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00],
        [0.00e+00, 6.20e-02, 0.00e+00, 0.00e+00, 0.00e+00],
        [0.00e+00, 0.00e+00, 2.00e-01, 0.00e+00, 0.00e+00],
        [0.00e+00, 0.00e+00, 0.00e+00, 1.56e+04, 0.00e+00],
        [0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 2.50e-01]]),
 array([[  0.25099801,   0.        ,   0.        ,   0.        ,
           0.        ],
        [  0.        ,   0.24899799,   0.        ,   0.        ,
           0.        ],
        [  0.        ,   0.        ,   0.4472136 ,   0.        ,
           0.        ],
        [  0.        ,   0.        ,   0.        , 124.89995997,
           0.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           0.5       ]]))

In [6]:
## Vectores "y" y "phi" Normalizados usando W
_y = np.dot(_W,ym)
_phi = np.dot(_W,phi)
_y, _phi

(array([1.75698606e-03, 8.73883353e+00, 2.70157261e+01, 9.47990696e+03,
        4.08045000e+01]),
 array([[2.50998008e-01, 0.00000000e+00, 0.00000000e+00],
        [2.48997992e-01, 2.48997992e-01, 2.48997992e-01],
        [4.47213595e-01, 8.94427191e-01, 1.78885438e+00],
        [1.24899960e+02, 3.74699880e+02, 1.12409964e+03],
        [5.00000000e-01, 2.00000000e+00, 8.00000000e+00]]))

In [7]:
## Calculando los estimados THETA
phi_pr = np.dot(_phi.transpose(),_phi)
A = np.linalg.inv(phi_pr)
B = np.dot(_phi.transpose(),_y)

## Vector Theta = parámetros estimados
# Esperado 0 , 40, -5
Theta = np.dot(A,B)
Esperado=np.array([0,40,-5])
print(f"Terminos Esperados: {Esperado[0]} {Esperado[1]} {Esperado[2]} Terminos Estimados: {round(Theta[0],5)} {round(Theta[1],5)} {round(Theta[2],5)}")

Terminos Esperados: 0 40 -5 Terminos Estimados: 0.0095 39.99023 -4.8978
